# frozen_string_literal: true

# Define error codes based on
# https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_concepts_core_data_objects.htm#statuscode
module Restforce
  module ErrorCode
    ERROR_CODES = {} # rubocop:disable Style/MutableConstant

    def self.add_error_code(error_code)
      return ERROR_CODES[error_code] if ERROR_CODES.key? error_code

      constant_name = error_code.to_s.split('_').map(&:capitalize).join.to_sym
      new_exception = const_set(constant_name, Class.new(ResponseError))

      ERROR_CODES[error_code] = new_exception

      new_exception
    end

    def self.get_exception_class(error_code)
      if ERROR_CODES.key? error_code
        ERROR_CODES[error_code]
      else
        warn "Unknown error code: #{error_code}\n" \
             'Please open an issue at https://github.com/restforce/restforce/issues/new/choose'

        add_error_code(error_code)
      end
    end

    %w[
      ALL_OR_NONE_OPERATION_ROLLED_BACK
      ALREADY_IN_PROCESS
      ASSIGNEE_TYPE_REQUIRED
      BAD_CUSTOM_ENTITY_PARENT_DOMAIN
      BCC_NOT_ALLOWED_IF_BCC_COMPLIANCE_ENABLED
      BCC_SELF_NOT_ALLOWED_IF_BCC_COMPLIANCE_ENABLED
      CANNOT_CASCADE_PRODUCT_ACTIVE
      CANNOT_CHANGE_FIELD_TYPE_OF_APEX_REFERENCED_FIELD
      CANNOT_CREATE_ANOTHER_MANAGED_PACKAGE
      CANNOT_DEACTIVATE_DIVISION
      CANNOT_DELETE_LAST_DATED_CONVERSION_RATE
      CANNOT_DELETE_MANAGED_OBJECT
      CANNOT_DISABLE_LAST_ADMIN
      CANNOT_ENABLE_IP_RESTRICT_REQUESTS
      CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY
      CANNOT_MODIFY_MANAGED_OBJECT
      CANNOT_RENAME_APEX_REFERENCED_FIELD
      CANNOT_RENAME_APEX_REFERENCED_OBJECT
      CANNOT_REPARENT_RECORD
      CANNOT_RESOLVE_NAME
      CANNOT_UPDATE_CONVERTED_LEAD
      CANT_DISABLE_CORP_CURRENCY
      CANT_UNSET_CORP_CURRENCY
      CHILD_SHARE_FAILS_PARENT
      CIRCULAR_DEPENDENCY
      COMMUNITY_NOT_ACCESSIBLE
      CUSTOM_CLOB_FIELD_LIMIT_EXCEEDED
      CUSTOM_ENTITY_OR_FIELD_LIMIT
      CUSTOM_FIELD_INDEX_LIMIT_EXCEEDED
      CUSTOM_INDEX_EXISTS
      CUSTOM_LINK_LIMIT_EXCEEDED
      CUSTOM_METADATA_LIMIT_EXCEEDED
      CUSTOM_SETTINGS_LIMIT_EXCEEDED
      CUSTOM_TAB_LIMIT_EXCEEDED
      DELETE_FAILED
      DEPENDENCY_EXISTS
      DUPLICATE_CASE_SOLUTION
      DUPLICATE_CUSTOM_ENTITY_DEFINITION
      DUPLICATE_CUSTOM_TAB_MOTIF
      DUPLICATE_DEVELOPER_NAME
      DUPLICATES_DETECTED
      DUPLICATE_EXTERNAL_ID
      DUPLICATE_MASTER_LABEL
      DUPLICATE_SENDER_DISPLAY_NAME
      DUPLICATE_USERNAME
      DUPLICATE_VALUE
      EMAIL_ADDRESS_BOUNCED
      EMAIL_NOT_PROCESSED_DUE_TO_PRIOR_ERROR
      EMAIL_OPTED_OUT
      EMAIL_TEMPLATE_FORMULA_ERROR
      EMAIL_TEMPLATE_MERGEFIELD_ACCESS_ERROR
      EMAIL_TEMPLATE_MERGEFIELD_ERROR
      EMAIL_TEMPLATE_MERGEFIELD_VALUE_ERROR
      EMAIL_TEMPLATE_PROCESSING_ERROR
      EMPTY_SCONTROL_FILE_NAME
      ENTITY_FAILED_IFLASTMODIFIED_ON_UPDATE
      ENTITY_IS_ARCHIVED
      ENTITY_IS_DELETED
      ENTITY_IS_LOCKED
      ENVIRONMENT_HUB_MEMBERSHIP_CONFLICT
      ERROR_IN_MAILER
      FAILED_ACTIVATION
      FIELD_CUSTOM_VALIDATION_EXCEPTION
      FIELD_FILTER_VALIDATION_EXCEPTION
      FILTERED_LOOKUP_LIMIT_EXCEEDED
      HTML_FILE_UPLOAD_NOT_ALLOWED
      IMAGE_TOO_LARGE
      INACTIVE_OWNER_OR_USER
      INSERT_UPDATE_DELETE_NOT_ALLOWED_DURING_MAINTENANCE
      INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY
      INSUFFICIENT_ACCESS_OR_READONLY
      INVALID_ACCESS_LEVEL
      INVALID_ARGUMENT_TYPE
      INVALID_ASSIGNEE_TYPE
      INVALID_ASSIGNMENT_RULE
      INVALID_BATCH_OPERATION
      INVALID_CONTENT_TYPE
      INVALID_CREDIT_CARD_INFO
      INVALID_CROSS_REFERENCE_KEY
      INVALID_CROSS_REFERENCE_TYPE_FOR_FIELD
      INVALID_CURRENCY_CONV_RATE
      INVALID_CURRENCY_CORP_RATE
      INVALID_CURRENCY_ISO
      INVALID_EMAIL_ADDRESS
      INVALID_EMPTY_KEY_OWNER
      INVALID_EVENT_SUBSCRIPTION
      INVALID_FIELD
      INVALID_FIELD_FOR_INSERT_UPDATE
      INVALID_FIELD_WHEN_USING_TEMPLATE
      INVALID_FILTER_ACTION
      INVALID_ID_FIELD
      INVALID_INET_ADDRESS
      INVALID_LINEITEM_CLONE_STATE
      INVALID_MASTER_OR_TRANSLATED_SOLUTION
      INVALID_MESSAGE_ID_REFERENCE
      INVALID_OPERATION
      INVALID_OPERATOR
      INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST
      INVALID_PARTNER_NETWORK_STATUS
      INVALID_PERSON_ACCOUNT_OPERATION
      INVALID_READ_ONLY_USER_DML
      INVALID_SAVE_AS_ACTIVITY_FLAG
      INVALID_SESSION_ID
      INVALID_STATUS
      INVALID_TYPE
      INVALID_TYPE_FOR_OPERATION
      INVALID_TYPE_ON_FIELD_IN_RECORD
      IP_RANGE_LIMIT_EXCEEDED
      JIGSAW_IMPORT_LIMIT_EXCEEDED
      LICENSE_LIMIT_EXCEEDED
      LIGHT_PORTAL_USER_EXCEPTION
      LIMIT_EXCEEDED
      LOGIN_CHALLENGE_ISSUED
      LOGIN_CHALLENGE_PENDING
      LOGIN_MUST_USE_SECURITY_TOKEN
      MALFORMED_ID
      MANAGER_NOT_DEFINED
      MASSMAIL_RETRY_LIMIT_EXCEEDED
      MASS_MAIL_LIMIT_EXCEEDED
      MAXIMUM_CCEMAILS_EXCEEDED
      MAXIMUM_DASHBOARD_COMPONENTS_EXCEEDED
      MAXIMUM_HIERARCHY_LEVELS_REACHED
      MAXIMUM_SIZE_OF_ATTACHMENT
      MAXIMUM_SIZE_OF_DOCUMENT
      MAX_ACTIONS_PER_RULE_EXCEEDED
      MAX_ACTIVE_RULES_EXCEEDED
      MAX_APPROVAL_STEPS_EXCEEDED
      MAX_FORMULAS_PER_RULE_EXCEEDED
      MAX_RULES_EXCEEDED
      MAX_RULE_ENTRIES_EXCEEDED
      MAX_TASK_DESCRIPTION_EXCEEDED
      MAX_TM_RULES_EXCEEDED
      MAX_TM_RULE_ITEMS_EXCEEDED
      MERGE_FAILED
      MISSING_ARGUMENT
      NONUNIQUE_SHIPPING_ADDRESS
      NO_APPLICABLE_PROCESS
      NO_ATTACHMENT_PERMISSION
      NO_INACTIVE_DIVISION_MEMBERS
      NO_MASS_MAIL_PERMISSION
      NUMBER_OUTSIDE_VALID_RANGE
      NUM_HISTORY_FIELDS_BY_SOBJECT_EXCEEDED
      OP_WITH_INVALID_USER_TYPE_EXCEPTION
      OPTED_OUT_OF_MASS_MAIL
      PACKAGE_LICENSE_REQUIRED
      PLATFORM_EVENT_ENCRYPTION_ERROR
      PLATFORM_EVENT_PUBLISHING_UNAVAILABLE
      PLATFORM_EVENT_PUBLISH_FAILED
      PORTAL_USER_ALREADY_EXISTS_FOR_CONTACT
      PRIVATE_CONTACT_ON_ASSET
      RECORD_IN_USE_BY_WORKFLOW
      REQUEST_RUNNING_TOO_LONG
      REQUIRED_FIELD_MISSING
      SELF_REFERENCE_FROM_TRIGGER
      SHARE_NEEDED_FOR_CHILD_OWNER
      SINGLE_EMAIL_LIMIT_EXCEEDED
      STANDARD_PRICE_NOT_DEFINED
      STORAGE_LIMIT_EXCEEDED
      STRING_TOO_LONG
      TABSET_LIMIT_EXCEEDED
      TEMPLATE_NOT_ACTIVE
      TERRITORY_REALIGN_IN_PROGRESS
      TEXT_DATA_OUTSIDE_SUPPORTED_CHARSET
      TOO_MANY_APEX_REQUESTS
      TOO_MANY_ENUM_VALUE
      TRANSFER_REQUIRES_READ
      UNABLE_TO_LOCK_ROW
      UNAVAILABLE_RECORDTYPE_EXCEPTION
      UNDELETE_FAILED
      UNKNOWN_EXCEPTION
      UNSPECIFIED_EMAIL_ADDRESS
      UNSUPPORTED_APEX_TRIGGER_OPERATION
      UNVERIFIED_SENDER_ADDRESS
      WEBLINK_SIZE_LIMIT_EXCEEDED
      WEBLINK_URL_INVALID
      WRONG_CONTROLLER_TYPE
    ].each { |error_code| add_error_code(error_code) }
  end
end
